--- 
# Main playbook

- hosts: all
  roles:
    - { role: clean, tags: clean }
    - { role: kube-install, tags: install }

- hosts: master
  roles:
    - { role: master-init, tags: master }

- hosts: nodes
  roles:
    - { role: add-nodes, tags: master }

- hosts: master
  tasks:
    - name: Container network 
      shell: "kubectl apply -f https://git.io/weave-kube-1.6"
  tags:
    - network
