# Tasks for initialising the master node

- name: "Initialise master"
  shell: "kubeadm init --token-ttl 0"
  become: true 
  register: output

- name: "Check if /.kube/config exists"
  stat:
    path: /home/ubuntu/.kube/config
  register: config_dir

- name: "Initialise cluster directory"
  shell: "mkdir -p /home/ubuntu/.kube/config/"
  when: config_dir.stat.exists == False

- name: "Get join token"
  set_fact:
    join_token: "{{ output.stdout | regex_search('kubeadm join.*') }}"
  
- debug:
    msg: "{{ join_token }}"

- name: "Create kube config"
  shell: "cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config && chown $(id -u):$(id -g) /home/ubuntu/.kube/config && export KUBECONFIG=/home/ubuntu/.kube/config/admin.conf"
  tags: 
    - config