# Tasks for adding worker nodes to the cluster

# Get token from master role variable
- set_fact:
    join_token: "{{ hostvars[groups['master'][0]]['join_token'] }}"
  tags:
    - token

- name: Join the cluster
  shell: "{{ join_token }}"
  become:
  tags:
    - token