# Tasks for installing kubeadm & kubectl

- name: "Get repo key"
  shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"
  become: true

- name: "Set up repo"
  shell: "echo 'deb http://apt.kubernetes.io/ kubernetes-xenial main' > /etc/apt/sources.list.d/kubernetes.list"
  become: true

- name: "Update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: "Check if kubeadm is installed"
  shell: "command -v kubeadm"
  register: kubeadm_exists
  ignore_errors: yes

- name: "Install kubeadm"
  apt:
    name: kubeadm
  when: kubeadm_exists.rc != 0
  become: true

- name: "Check if kubectl is installed"
  shell: "command -v kubectl"
  register: kubectl_exists
  ignore_errors: yes

- name: "Install kubectl"
  apt:
    name: kubectl
  when: kubectl_exists.rc != 0
  become: true